### ISSUE TITLE
🗺️  Roadmap to 1.0

### ISSUE THREAD

**Issue by roginfarrer** [system-props/system-props#2]
* [x] Fix TypeScript types for system props usage on components
* [x] Complete documentation website
  * [x] Comparison to styled-system
  * [x] When, why, and how to use `$` syntax
  * [x] Theme specification

**Comment by roginfarrer** [comment]
Closing this issue for now, it's not very useful
